repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "f350497a11b1285c695595049e95a420068e7a9f"
    hooks:
      - id: flutter-import-sorter

  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
    hooks:
      - id: flutter-analyze
