include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    todo: ignore
  exclude:

linter:
  rules:
    sort_pub_dependencies: false