name: tat
description: NTUT Life TAT, convenient, concise, fast, powerful, enrich your NTUT life!

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:

  flutter:
    sdk: flutter

  # TAT Core implementations.
  # Use https login with github personal access key at the first time to obtain this sub-package.
  tat_core:
    git:
      url: git@github.com:Xanonymous-GitHub/TAT-Core.git
      ref: main

  # Bloc for implement the Bloc design pattern.
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  sealed_flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  replay_bloc: ^0.2.1

  # Get
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  # App configurations
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2

  # Bloc
  bloc_test: ^9.0.1
  bloc_tools: ^0.1.0-dev.4

module:
  androidX: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: TATFont
      fonts:
        - asset: assets/fonts/GenSenRounded-R.ttc
          weight: 400
        - asset: assets/fonts/GenSenRounded-B.ttc
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tat.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png

  color_dark: "#2b2b2b"
  image_dark: assets/images/splash-dark.png

  android: true
  android_gravity: center

  ios: true
  ios_content_mode: center

  fullscreen: true
