name: tat
description: NTUT Life TAT, convenient, concise, fast, powerful, enrich your NTUT life!

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  # Bloc for implement the Bloc design pattern.
  bloc: ^8.0.0-dev.4
  flutter_bloc: ^8.0.0-dev.2
  hydrated_bloc: ^8.0.0-dev.3
  sealed_flutter_bloc: ^8.0.0-dev.1
  bloc_concurrency: ^0.2.0-dev.1
  replay_bloc: ^0.2.0-dev.2

  # Get
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  # App configurations
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

  # Bloc
  bloc_test: ^9.0.0-dev.4
  bloc_tools: ^0.1.0-dev.4

module:
  androidX: true

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tat.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png

  color_dark: "#2b2b2b"
  image_dark: assets/images/splash-dark.png

  android: true
  android_gravity: center

  ios: true
  ios_content_mode: center

  fullscreen: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
