name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  
  build-ios:
  
    name: Build iOS
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ macos-latest ]
        
    steps:
    
    # checkout codebase.
    - name: Checkout codebase
      uses: actions/checkout@v2
    
    # Set up Flutter.
    - name: Clone Flutter repository with stable channel
      uses: subosito/flutter-action@v1
      with:
        channel: stable

    # Checkout gallery code and get packages.
    - name: Get dependencies
      run: flutter pub get
    
    # Build ios app
    - name: Build app
      run: flutter build ios --no-codesign
    
  build-aos:
  
    name: Build AOS
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ macos-latest ]
        
    steps:
    
    # checkout codebase.
    - name: Checkout codebase
      uses: actions/checkout@v2
    
    # Set up Java.
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Clone Flutter repository with stable channel
      uses: subosito/flutter-action@v1
      with:
        channel: stable

    # Get packages.
    - name: Get dependencies
      run: flutter pub get
    
    # Build aos app
    - name: Build appbundle
      run: flutter build appbundle --debug
      
